language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      script: ./gradlew assemble
    - stage: test
      script: ./gradlew check
notifications:
  on_success: change # default: always
  on_failure: always # default: always
